force-app/main/default/objects/Rate__mdt/Rate__mdt.object-meta.xml
<CustomObject>
    <label>Rate</label>
    <pluralLabel>Rates</pluralLabel>
</CustomObject>

force-app/main/default/objects/Rate__mdt/fields/Rate_for_0_To_499__c.field-meta.xml
<CustomField>
    <fullName>Rate_for_0_To_499__c</fullName>
    <label>Rate for 0 To 499</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rate__mdt/fields/Rate_for_1000_To_1499__c.field-meta.xml
<CustomField>
    <fullName>Rate_for_1000_To_1499__c</fullName>
    <label>Rate for 1000 To 1499</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rate__mdt/fields/Rate_for_1500__c.field-meta.xml
<CustomField>
    <fullName>Rate_for_1500__c</fullName>
    <label>Rate for 1500+</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rate__mdt/fields/Rate_for_500_To_999__c.field-meta.xml
<CustomField>
    <fullName>Rate_for_500_To_999__c</fullName>
    <label>Rate for 500 To 999</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/metaDataClass.cls
public class metaDataClass {
    public static void methodd(List<Contact> conList){
        if(conList != null && !conList.isEmpty() ){
            List<Rate__mdt>  rates =[select Id,Rate_for_0_To_499__c,Rate_for_500_To_999__c,Rate_for_1000_To_1499__c,Rate_for_1500__c
                                     from Rate__mdt limit 1 ];
            if(rates != null && !rates.isEmpty()){
                for(Contact con : conList){
                    if(String.isNotBlank(con.TotalCaseResolved__c)){
                    if(con.TotalCaseResolved__c =='0 To 499'){
                        con.Amount_New__c = rates[0].Rate_for_0_To_499__c;
                    }else if(con.TotalCaseResolved__c =='500 To 999'){
                         con.Amount_New__c = rates[0].Rate_for_500_To_999__c;
                    }else if(con.TotalCaseResolved__c =='1000 To 1499'){
                         con.Amount_New__c = rates[0].Rate_for_1000_To_1499__c;
                    }else{
                        con.Amount_New__c = rates[0].Rate_for_1500__c;
                    }
                    }}
            }
        }
        
        
    }

}